name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  deploy:
    name: "NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" Feli.AspNet.Authentication.Discord/Feli.AspNet.Authentication.Discord.csproj"        
    - name: Build
      run: dotnet build Feli.AspNet.Authentication.Discord/Feli.AspNet.Authentication.Discord.csproj --configuration Release --no-restore
    - name: Push to NuGet
      run: dotnet nuget push Feli.AspNet.Authentication.Discord/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
    - name: Push to GitHub
      run: dotnet nuget push Feli.AspNet.Authentication.Discord/bin/Release/*.nupkg
             --api-key ${{ secrets.GITHUB_TOKEN }}
             --source "github"
